Repository Likelion-Hongik-Site/Likelion-Hongik-Site-Frontend, pull requests merged in 2025-02, with the labels that each got.

#19 [Fix] SideBar 이슈 해결 및 기능 추가 / Contact ProfileCard gap 수정
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/components/pages/contact/ProfileCardList.tsx
  src/pages/ContactPage.tsx
  src/pages/HomePage.tsx
Labels: 🐛 Bug, ✨ Feature, 🎨 Design

#18 [Feat] Recruit 페이지 phone UI 구현
  src/components/Recruit/ScheduleBar.tsx
  src/components/Recruit/ScheduleContent.tsx
  src/components/pages/recruit/ScheduleBar.tsx
  src/components/pages/recruit/ScheduleContent.tsx
  src/components/pages/recruit/ScheduleItem.tsx
  src/components/pages/recruit/ScheduleLines.tsx
  src/data/ScheduleData.ts
  src/data/TrackData.ts
  src/pages/RecruitPage.tsx
Labels: ✨ Feature, 🎨 Design

#20 [Fix] Recruit 페이지 1220px 내 440px 사이즈로 고정
  src/assets/webps/recruit/bulbImg.webp
  src/assets/webps/recruit/devImg.webp
  src/assets/webps/recruit/monitorImg.webp
  src/components/pages/recruit/ScheduleBar.tsx
  src/components/pages/recruit/ScheduleContent.tsx
  src/components/pages/recruit/ScheduleLines.tsx
  src/data/TrackData.ts
  src/pages/RecruitPage.tsx
Labels: 🐛 Bug

#21 [Fix] SideBar fixed로 고정 & 오류 수정
  src/components/layout/Layout.tsx
  src/components/layout/Navbar.tsx
  src/pages/HomePage.tsx
Labels: 🐛 Bug, 🎨 Design

#23 [Design] Navbar 로고 수정 / Contact 프로필 삽입
  src/assets/webps/layout/likelion.webp
  src/assets/webps/pages/contact/profile1.webp
  src/assets/webps/pages/contact/profile2.webp
  src/assets/webps/pages/contact/profile3.webp
  src/assets/webps/pages/contact/profile4.webp
  src/assets/webps/pages/contact/profile5.webp
  src/assets/webps/pages/contact/profile6.webp
  src/assets/webps/pages/contact/profile7.webp
  src/assets/webps/pages/contact/profile8.webp
  src/assets/webps/pages/recruit/bulbImg.webp
  src/assets/webps/pages/recruit/devImg.webp
  src/assets/webps/pages/recruit/monitorImg.webp
  src/components/layout/Navbar.tsx
  src/components/pages/contact/ProfileCard.tsx
  src/data/ProfileData.ts
  src/data/TrackData.ts
Labels: 🎨 Design

#24 [Fix] Recruit 페이지 이미지/ 버튼 색상 변경 및 구글폼 추가
  src/assets/webps/pages/recruit/devImg.webp
  src/assets/webps/pages/recruit/monitorImg.webp
  src/data/ProfileData.ts
  src/index.css
  src/pages/RecruitPage.tsx
Labels: 🎨 Design

#26 [Fix] gradientCursor 440px 이하에서 숨김 & swiper 이미지 크기 조정
  src/components/ui/gradientCursor.tsx
  src/index.css
Labels: 🐛 Bug

#27 [Merge] 배포 이후 수정
  src/components/ui/gradientCursor.tsx
  src/index.css
Labels: 🐛 Bug

#28 [Fix] 375px 내 좌우 스크롤 여백 수정
  src/components/pages/recruit/ScheduleContent.tsx
Labels: 🐛 Bug

#29 [Merge] QA 적용
  index.html
  public/thumbnail.png
  src/assets/webps/pages/archive/review/37.webp
  src/components/layout/Layout.tsx
  src/components/pages/archive/Project.tsx
  src/components/pages/archive/Review.tsx
  src/components/pages/archive/Reviewph.tsx
  src/components/pages/recruit/ScheduleContent.tsx
  src/pages/ContactPage.tsx
Labels: 🐛 Bug

#30 [Merge] QA 반영
  index.html
  public/thumbnail.png
  src/assets/webps/pages/archive/review/37.webp
  src/components/layout/Layout.tsx
  src/components/pages/archive/Project.tsx
  src/components/pages/archive/Review.tsx
  src/components/pages/archive/Reviewph.tsx
  src/components/pages/recruit/ScheduleContent.tsx
  src/pages/ContactPage.tsx
Labels: 🐛 Bug

#31 [Fix] text 색 수정 & 37 review 클릭 시 모달 오픈 추가
  src/components/pages/archive/Reviewph.tsx
  src/pages/ContactPage.tsx
Labels: 🐛 Bug
